/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package finallogica.Interfaz;

import finallogica.Clases.Estudiante;
import finallogica.Modelo.SolicitudGrados;
import javax.swing.JOptionPane;

/**
 *
 * @author gerso
 */
public class IngresoEstudiante extends javax.swing.JFrame {

    private int IdSesion;
    /**
     * Creates new form IngresoEstudiante
     */
    public IngresoEstudiante(int IdSesion) {
        this.IdSesion = IdSesion;
        initComponents();
        LbSubtitulo.setText(ClasePrincipal.estudiante.get(IdSesion).getNombre() + " " + ClasePrincipal.estudiante.get(IdSesion).getApellido());
                if (ClasePrincipal.estudiante.get(IdSesion).getEstado_graduacion().EGRESADO != Estudiante.estado_graduacion.EGRESADO) {
            BtSolicitud.setEnabled(false);
    } else if (ClasePrincipal.estudiante.get(IdSesion).getEstado_graduacion().PENDIENTE == Estudiante.estado_graduacion.PENDIENTE) {
        BtSolicitud.setEnabled(false);
    }
                
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LbTitulo = new javax.swing.JLabel();
        LbSubtitulo = new javax.swing.JLabel();
        LbImg = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        BtSolicitud = new javax.swing.JButton();
        BtMostrar = new javax.swing.JButton();
        BtEstado = new javax.swing.JButton();
        BtSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(ClasePrincipal.favicon);
        setResizable(false);

        LbTitulo.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        LbTitulo.setText("Bienvenido/a");

        LbSubtitulo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LbSubtitulo.setText("Estudiante");

        LbImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finallogica/Interfaz/img/deco.png"))); // NOI18N
        LbImg.setText("LogoPlaceholder");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Operaciones", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        BtSolicitud.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        BtSolicitud.setText("Realizar Solicitud");
        BtSolicitud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtSolicitudActionPerformed(evt);
            }
        });

        BtMostrar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        BtMostrar.setText("Mostrar mis datos");

        BtEstado.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        BtEstado.setText("Ver estado de la solicitud");
        BtEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtEstadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtSolicitud, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtMostrar, javax.swing.GroupLayout.DEFAULT_SIZE, 486, Short.MAX_VALUE)
                    .addComponent(BtEstado, javax.swing.GroupLayout.DEFAULT_SIZE, 486, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BtSolicitud, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtMostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        BtSalir.setText("Cerrar Sesión");
        BtSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BtSalir, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LbSubtitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LbTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LbImg, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LbImg, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(LbTitulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LbSubtitulo)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtSalir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtSalirActionPerformed
        new Inicio().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtSalirActionPerformed

    private void BtEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtEstadoActionPerformed

    private void BtSolicitudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtSolicitudActionPerformed

        if (SolicitudGrados.SolicitarGrados(IdSesion)) {
            JOptionPane.showMessageDialog(null, "Se ha colocado la solicitud.", "Estado de la solicitud", JOptionPane.INFORMATION_MESSAGE);
            return;
        } else {
            return;
        }
    }//GEN-LAST:event_BtSolicitudActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtEstado;
    private javax.swing.JButton BtMostrar;
    private javax.swing.JButton BtSalir;
    private javax.swing.JButton BtSolicitud;
    private javax.swing.JLabel LbImg;
    private javax.swing.JLabel LbSubtitulo;
    private javax.swing.JLabel LbTitulo;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
