/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package finallogica.Interfaz;


import javax.swing.JOptionPane;

/**
 *
 * @author Maria Camila
 */
public class MainEstudiante extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public MainEstudiante() {
        this.setUndecorated(true);
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LbPanel = new javax.swing.JLabel();
        LbCuadrados = new javax.swing.JLabel();
        LbSalirSistema = new javax.swing.JLabel();
        LbMinimizar = new javax.swing.JLabel();
        LbBarraSuperior = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        LbBienvenido = new javax.swing.JLabel();
        LbEstudiante = new javax.swing.JLabel();
        LbImagenDirectivo = new javax.swing.JLabel();
        SeparadorPanel = new javax.swing.JSeparator();
        BtCerrarSesion = new javax.swing.JButton();
        JpPanelInicio = new javax.swing.JPanel();
        LbImgPanelInicio = new javax.swing.JLabel();
        LbPanelInicio = new javax.swing.JLabel();
        JpRegistros = new javax.swing.JPanel();
        LbImgRegistros = new javax.swing.JLabel();
        LbRegistros = new javax.swing.JLabel();
        JpSolicitudes = new javax.swing.JPanel();
        LbImgSolicitudes = new javax.swing.JLabel();
        LbSolicitudes = new javax.swing.JLabel();
        JpEstadisticas = new javax.swing.JPanel();
        LbImgEstadisticas = new javax.swing.JLabel();
        LbEstadisticas = new javax.swing.JLabel();
        TbPanelDirectivo = new javax.swing.JTabbedPane();
        JpInicio = new javax.swing.JPanel();
        LbImgInfo = new javax.swing.JLabel();
        JpTablaRegistros = new javax.swing.JPanel();
        LbBienvenido1 = new javax.swing.JLabel();
        JpTablaSolicitudes = new javax.swing.JPanel();
        LbBienvenido2 = new javax.swing.JLabel();
        JpTablaEstadisticas = new javax.swing.JPanel();
        LbBienvenido3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setAutoRequestFocus(false);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LbPanel.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        LbPanel.setForeground(new java.awt.Color(255, 255, 255));
        LbPanel.setText("Panel");
        getContentPane().add(LbPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, -1, 29));

        LbCuadrados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finallogica/Interfaz/img/cuadrados.png"))); // NOI18N
        getContentPane().add(LbCuadrados, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, -1, -1));

        LbSalirSistema.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finallogica/Interfaz/img/x.png"))); // NOI18N
        LbSalirSistema.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LbSalirSistemaMouseClicked(evt);
            }
        });
        getContentPane().add(LbSalirSistema, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 20, -1, -1));

        LbMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finallogica/Interfaz/img/flecha-hacia-abajo-para-navegar.png"))); // NOI18N
        LbMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LbMinimizarMouseClicked(evt);
            }
        });
        getContentPane().add(LbMinimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 20, -1, 20));

        LbBarraSuperior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finallogica/Interfaz/img/Fondo3.png"))); // NOI18N
        getContentPane().add(LbBarraSuperior, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 810, 70));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LbBienvenido.setBackground(new java.awt.Color(0, 51, 255));
        LbBienvenido.setFont(new java.awt.Font("Yu Gothic UI", 1, 36)); // NOI18N
        LbBienvenido.setForeground(new java.awt.Color(0, 51, 255));
        LbBienvenido.setText("Bienvenido");
        jPanel4.add(LbBienvenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 150, -1, 30));

        LbEstudiante.setBackground(new java.awt.Color(0, 153, 255));
        LbEstudiante.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        LbEstudiante.setForeground(new java.awt.Color(0, 204, 255));
        LbEstudiante.setText("Estudiante");
        jPanel4.add(LbEstudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, -1, 20));

        LbImagenDirectivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finallogica/Interfaz/img/usuario (6).png"))); // NOI18N
        jPanel4.add(LbImagenDirectivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 20, -1, -1));

        SeparadorPanel.setForeground(new java.awt.Color(0, 51, 255));
        jPanel4.add(SeparadorPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 240, 240, 10));

        BtCerrarSesion.setBackground(new java.awt.Color(0, 51, 255));
        BtCerrarSesion.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        BtCerrarSesion.setForeground(new java.awt.Color(255, 255, 255));
        BtCerrarSesion.setText("Cerrar Sesión");
        BtCerrarSesion.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtCerrarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtCerrarSesionActionPerformed(evt);
            }
        });
        jPanel4.add(BtCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 480, 130, 44));

        JpPanelInicio.setBackground(new java.awt.Color(255, 255, 255));
        JpPanelInicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JpPanelInicio.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                JpPanelInicioMouseMoved(evt);
            }
        });
        JpPanelInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JpPanelInicioMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JpPanelInicioMouseExited(evt);
            }
        });

        LbImgPanelInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finallogica/Interfaz/img/hogar.png"))); // NOI18N

        LbPanelInicio.setBackground(new java.awt.Color(255, 255, 255));
        LbPanelInicio.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        LbPanelInicio.setForeground(new java.awt.Color(102, 102, 102));
        LbPanelInicio.setText("Inicio");

        javax.swing.GroupLayout JpPanelInicioLayout = new javax.swing.GroupLayout(JpPanelInicio);
        JpPanelInicio.setLayout(JpPanelInicioLayout);
        JpPanelInicioLayout.setHorizontalGroup(
            JpPanelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpPanelInicioLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(LbImgPanelInicio)
                .addGap(29, 29, 29)
                .addComponent(LbPanelInicio)
                .addContainerGap(77, Short.MAX_VALUE))
        );
        JpPanelInicioLayout.setVerticalGroup(
            JpPanelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpPanelInicioLayout.createSequentialGroup()
                .addComponent(LbImgPanelInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
            .addComponent(LbPanelInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel4.add(JpPanelInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 230, -1));

        JpRegistros.setBackground(new java.awt.Color(255, 255, 255));
        JpRegistros.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JpRegistros.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                JpRegistrosMouseMoved(evt);
            }
        });
        JpRegistros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JpRegistrosMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JpRegistrosMouseExited(evt);
            }
        });

        LbImgRegistros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finallogica/Interfaz/img/compartir.png"))); // NOI18N

        LbRegistros.setBackground(new java.awt.Color(255, 255, 255));
        LbRegistros.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        LbRegistros.setForeground(new java.awt.Color(102, 102, 102));
        LbRegistros.setText("Registros");

        javax.swing.GroupLayout JpRegistrosLayout = new javax.swing.GroupLayout(JpRegistros);
        JpRegistros.setLayout(JpRegistrosLayout);
        JpRegistrosLayout.setHorizontalGroup(
            JpRegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpRegistrosLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(LbImgRegistros)
                .addGap(29, 29, 29)
                .addComponent(LbRegistros)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        JpRegistrosLayout.setVerticalGroup(
            JpRegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpRegistrosLayout.createSequentialGroup()
                .addComponent(LbImgRegistros, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
            .addComponent(LbRegistros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel4.add(JpRegistros, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 230, -1));

        JpSolicitudes.setBackground(new java.awt.Color(255, 255, 255));
        JpSolicitudes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JpSolicitudes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JpSolicitudesMouseClicked(evt);
            }
        });

        LbImgSolicitudes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finallogica/Interfaz/img/mensaje.png"))); // NOI18N

        LbSolicitudes.setBackground(new java.awt.Color(255, 255, 255));
        LbSolicitudes.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        LbSolicitudes.setForeground(new java.awt.Color(102, 102, 102));
        LbSolicitudes.setText("Solicitudes");

        javax.swing.GroupLayout JpSolicitudesLayout = new javax.swing.GroupLayout(JpSolicitudes);
        JpSolicitudes.setLayout(JpSolicitudesLayout);
        JpSolicitudesLayout.setHorizontalGroup(
            JpSolicitudesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpSolicitudesLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(LbImgSolicitudes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(LbSolicitudes)
                .addGap(21, 21, 21))
        );
        JpSolicitudesLayout.setVerticalGroup(
            JpSolicitudesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpSolicitudesLayout.createSequentialGroup()
                .addComponent(LbImgSolicitudes, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
            .addComponent(LbSolicitudes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel4.add(JpSolicitudes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 230, -1));

        JpEstadisticas.setBackground(new java.awt.Color(255, 255, 255));
        JpEstadisticas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JpEstadisticas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JpEstadisticasMouseClicked(evt);
            }
        });

        LbImgEstadisticas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finallogica/Interfaz/img/ojo.png"))); // NOI18N

        LbEstadisticas.setBackground(new java.awt.Color(255, 255, 255));
        LbEstadisticas.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        LbEstadisticas.setForeground(new java.awt.Color(102, 102, 102));
        LbEstadisticas.setText("Estadísticas");

        javax.swing.GroupLayout JpEstadisticasLayout = new javax.swing.GroupLayout(JpEstadisticas);
        JpEstadisticas.setLayout(JpEstadisticasLayout);
        JpEstadisticasLayout.setHorizontalGroup(
            JpEstadisticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpEstadisticasLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(LbImgEstadisticas)
                .addGap(28, 28, 28)
                .addComponent(LbEstadisticas)
                .addContainerGap(12, Short.MAX_VALUE))
        );
        JpEstadisticasLayout.setVerticalGroup(
            JpEstadisticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpEstadisticasLayout.createSequentialGroup()
                .addGroup(JpEstadisticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LbImgEstadisticas, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LbEstadisticas, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 6, Short.MAX_VALUE))
        );

        jPanel4.add(JpEstadisticas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 230, -1));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 580));

        JpInicio.setBackground(new java.awt.Color(255, 255, 255));

        LbImgInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finallogica/Interfaz/img/fondoestudiante.png"))); // NOI18N

        javax.swing.GroupLayout JpInicioLayout = new javax.swing.GroupLayout(JpInicio);
        JpInicio.setLayout(JpInicioLayout);
        JpInicioLayout.setHorizontalGroup(
            JpInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LbImgInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 810, Short.MAX_VALUE)
        );
        JpInicioLayout.setVerticalGroup(
            JpInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpInicioLayout.createSequentialGroup()
                .addComponent(LbImgInfo)
                .addGap(0, 20, Short.MAX_VALUE))
        );

        TbPanelDirectivo.addTab("tab1", JpInicio);

        JpTablaRegistros.setBackground(new java.awt.Color(255, 255, 255));

        LbBienvenido1.setBackground(new java.awt.Color(0, 51, 255));
        LbBienvenido1.setFont(new java.awt.Font("Yu Gothic UI", 1, 36)); // NOI18N
        LbBienvenido1.setForeground(new java.awt.Color(0, 51, 255));
        LbBienvenido1.setText("Registros");

        javax.swing.GroupLayout JpTablaRegistrosLayout = new javax.swing.GroupLayout(JpTablaRegistros);
        JpTablaRegistros.setLayout(JpTablaRegistrosLayout);
        JpTablaRegistrosLayout.setHorizontalGroup(
            JpTablaRegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 810, Short.MAX_VALUE)
            .addGroup(JpTablaRegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(JpTablaRegistrosLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(LbBienvenido1)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        JpTablaRegistrosLayout.setVerticalGroup(
            JpTablaRegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 535, Short.MAX_VALUE)
            .addGroup(JpTablaRegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(JpTablaRegistrosLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(LbBienvenido1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        TbPanelDirectivo.addTab("tab2", JpTablaRegistros);

        JpTablaSolicitudes.setBackground(new java.awt.Color(255, 255, 255));

        LbBienvenido2.setBackground(new java.awt.Color(0, 51, 255));
        LbBienvenido2.setFont(new java.awt.Font("Yu Gothic UI", 1, 36)); // NOI18N
        LbBienvenido2.setForeground(new java.awt.Color(0, 51, 255));
        LbBienvenido2.setText("Solicitudes");

        javax.swing.GroupLayout JpTablaSolicitudesLayout = new javax.swing.GroupLayout(JpTablaSolicitudes);
        JpTablaSolicitudes.setLayout(JpTablaSolicitudesLayout);
        JpTablaSolicitudesLayout.setHorizontalGroup(
            JpTablaSolicitudesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 810, Short.MAX_VALUE)
            .addGroup(JpTablaSolicitudesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(JpTablaSolicitudesLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(LbBienvenido2)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        JpTablaSolicitudesLayout.setVerticalGroup(
            JpTablaSolicitudesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 535, Short.MAX_VALUE)
            .addGroup(JpTablaSolicitudesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(JpTablaSolicitudesLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(LbBienvenido2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        TbPanelDirectivo.addTab("tab3", JpTablaSolicitudes);

        JpTablaEstadisticas.setBackground(new java.awt.Color(255, 255, 255));

        LbBienvenido3.setBackground(new java.awt.Color(0, 51, 255));
        LbBienvenido3.setFont(new java.awt.Font("Yu Gothic UI", 1, 36)); // NOI18N
        LbBienvenido3.setForeground(new java.awt.Color(0, 51, 255));
        LbBienvenido3.setText("Estadísticas");

        javax.swing.GroupLayout JpTablaEstadisticasLayout = new javax.swing.GroupLayout(JpTablaEstadisticas);
        JpTablaEstadisticas.setLayout(JpTablaEstadisticasLayout);
        JpTablaEstadisticasLayout.setHorizontalGroup(
            JpTablaEstadisticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 810, Short.MAX_VALUE)
            .addGroup(JpTablaEstadisticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(JpTablaEstadisticasLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(LbBienvenido3)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        JpTablaEstadisticasLayout.setVerticalGroup(
            JpTablaEstadisticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 535, Short.MAX_VALUE)
            .addGroup(JpTablaEstadisticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(JpTablaEstadisticasLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(LbBienvenido3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        TbPanelDirectivo.addTab("tab4", JpTablaEstadisticas);

        getContentPane().add(TbPanelDirectivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, 810, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LbMinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LbMinimizarMouseClicked
        this.setState(Login.ICONIFIED);
    }//GEN-LAST:event_LbMinimizarMouseClicked

    private void BtCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtCerrarSesionActionPerformed
        Inicio.IdSesion = -1;
        new Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtCerrarSesionActionPerformed

    private void JpPanelInicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JpPanelInicioMouseClicked
        TbPanelDirectivo.setSelectedIndex(0);
    }//GEN-LAST:event_JpPanelInicioMouseClicked

    private void JpPanelInicioMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JpPanelInicioMouseMoved

    }//GEN-LAST:event_JpPanelInicioMouseMoved

    private void JpPanelInicioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JpPanelInicioMouseExited
        
    }//GEN-LAST:event_JpPanelInicioMouseExited

    private void JpSolicitudesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JpSolicitudesMouseClicked
        TbPanelDirectivo.setSelectedIndex(2);
    }//GEN-LAST:event_JpSolicitudesMouseClicked

    private void JpEstadisticasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JpEstadisticasMouseClicked
        TbPanelDirectivo.setSelectedIndex(3);
    }//GEN-LAST:event_JpEstadisticasMouseClicked

    private void JpRegistrosMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JpRegistrosMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_JpRegistrosMouseMoved

    private void JpRegistrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JpRegistrosMouseClicked
        TbPanelDirectivo.setSelectedIndex(1);
    }//GEN-LAST:event_JpRegistrosMouseClicked

    private void JpRegistrosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JpRegistrosMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_JpRegistrosMouseExited

    private void LbSalirSistemaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LbSalirSistemaMouseClicked
       int dialog = JOptionPane.YES_NO_OPTION;
        int result = JOptionPane.showConfirmDialog(null, "Desea salir del sistema?","Exit", dialog);
        if(result ==0){
            System.exit(0);
        }
    }//GEN-LAST:event_LbSalirSistemaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainEstudiante().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtCerrarSesion;
    private javax.swing.JPanel JpEstadisticas;
    private javax.swing.JPanel JpInicio;
    private javax.swing.JPanel JpPanelInicio;
    private javax.swing.JPanel JpRegistros;
    private javax.swing.JPanel JpSolicitudes;
    private javax.swing.JPanel JpTablaEstadisticas;
    private javax.swing.JPanel JpTablaRegistros;
    private javax.swing.JPanel JpTablaSolicitudes;
    private javax.swing.JLabel LbBarraSuperior;
    private javax.swing.JLabel LbBienvenido;
    private javax.swing.JLabel LbBienvenido1;
    private javax.swing.JLabel LbBienvenido2;
    private javax.swing.JLabel LbBienvenido3;
    private javax.swing.JLabel LbCuadrados;
    private javax.swing.JLabel LbEstadisticas;
    private javax.swing.JLabel LbEstudiante;
    private javax.swing.JLabel LbImagenDirectivo;
    private javax.swing.JLabel LbImgEstadisticas;
    private javax.swing.JLabel LbImgInfo;
    private javax.swing.JLabel LbImgPanelInicio;
    private javax.swing.JLabel LbImgRegistros;
    private javax.swing.JLabel LbImgSolicitudes;
    private javax.swing.JLabel LbMinimizar;
    private javax.swing.JLabel LbPanel;
    private javax.swing.JLabel LbPanelInicio;
    private javax.swing.JLabel LbRegistros;
    private javax.swing.JLabel LbSalirSistema;
    private javax.swing.JLabel LbSolicitudes;
    private javax.swing.JSeparator SeparadorPanel;
    private javax.swing.JTabbedPane TbPanelDirectivo;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
