    /*
 * 
 */
package finallogica.Interfaz.Registros;

import finallogica.Clases.Carrera;
import finallogica.Clases.Estudiante;
import finallogica.Clases.Fijas.Posgrado;
import finallogica.Clases.Fijas.Pregrado;
import finallogica.Interfaz.ClasePrincipal;
import finallogica.Modelo.Operaciones;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import java.awt.event.WindowEvent;
import java.awt.event.WindowStateListener;
import javax.swing.JOptionPane;

/**
 *
 * @author AntJZ
 */
public class Asistente extends javax.swing.JFrame {
    private static SeleccionarRegistroPrePos registroPrePos = new SeleccionarRegistroPrePos();
    Object data;
    int index; 
    int data_index;
    /**
     *  ASISTENTE.
     * Esta clase crea una nueva entrada, dependiendo del tipo de dato.
     * @param index Recibe el índice de la lista [Estudiante, TrabajoDeGrado, Pregrado, Posgrado]
     * 
     * @data recibe un dato, y el programa reconoce si es un estudiante
     *        o carrera.
     * @index se recibe si no se va a modificar un dato, sino que solamente
     *        lo agrega.
     * 
     */
     public Asistente(int index) {
        this.index = index;
        initComponents();
        LbTitulo.setText("Agregar Datos");
        // Averiguar que tipo de dato es
        switch (index) {
            case 0:
                // Estudiantes
                // Limpieza
        TfEstudianteTipoDocumento.setSelectedItem(null);
        TfEstudianteEstGraduacion.setSelectedItem(null);
        TfEstudianteEstMatricula.setSelectedItem(null);
        TfEstudianteCarrera.setText("Click acá para seleccionar...");
                // Se esconden los otros combos.
                TpTipo.remove(PanelPosgrado);
                TpTipo.remove(PanelPregrado);
                break;
            case 1:
                // Trabajos de grado
                TpTipo.remove(PanelPosgrado);
                TpTipo.remove(PanelEstudiante);
                TpTipo.remove(PanelPregrado);
                break;
            case 2:
                // Pregrados
                TpTipo.remove(PanelPosgrado);
                TpTipo.remove(PanelEstudiante);
                break;
            case 3:
                // Posgrados
                TpTipo.remove(PanelEstudiante);
                TpTipo.remove(PanelPregrado);
                break;
            default:
                JOptionPane.showMessageDialog(null, "Corre el programa desde la clase principal, ya que no se han cargado aún los datos...");
                this.dispose();
        }
    }
    
    public Asistente(int data_index, Object data) {
        this.data = data;
        this.data_index = data_index;
        initComponents();
        // Averiguar que tipo de dato es
        index = Operaciones.buscarTipo(data);
        switch (index) {
            case 0:
                // Estudiantes
                TpTipo.remove(PanelPosgrado);
                TpTipo.remove(PanelPregrado);
                break;
            case 1:
                // Trabajos de grado
                TpTipo.remove(PanelPosgrado);
                TpTipo.remove(PanelPregrado);
                TpTipo.remove(PanelEstudiante);
                break;
            case 2:
                // Pregrados
                TpTipo.remove(PanelPosgrado);
                TpTipo.remove(PanelEstudiante);
                break;
            case 3:
                // Posgrados
                TpTipo.remove(PanelEstudiante);
                TpTipo.remove(PanelPregrado);
                break;
            default:
                JOptionPane.showMessageDialog(null, "Corre el programa desde la clase principal, ya que no se han cargado aún los datos...");
                this.dispose();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LbEstudianteNombre2 = new javax.swing.JLabel();
        TfEstudianteNombre2 = new javax.swing.JTextField();
        LbImg = new javax.swing.JLabel();
        LbTitulo = new javax.swing.JLabel();
        BtCerrar = new javax.swing.JButton();
        BtAlmacenar = new javax.swing.JButton();
        TpTipo = new javax.swing.JTabbedPane();
        PanelEstudiante = new javax.swing.JPanel();
        LbEstudianteNombre = new javax.swing.JLabel();
        TfEstudianteNombre = new javax.swing.JTextField();
        LbEstudianteApellido = new javax.swing.JLabel();
        TfEstudianteApellido = new javax.swing.JTextField();
        LbEstudianteTipoDocumento = new javax.swing.JLabel();
        TfEstudianteTipoDocumento = new javax.swing.JComboBox<>();
        LbEstudianteNumDocumento = new javax.swing.JLabel();
        TfEstudianteNumDocumento = new javax.swing.JTextField();
        LbEstudianteNumTelefono = new javax.swing.JLabel();
        TfEstudianteNumTelefono = new javax.swing.JTextField();
        LbEstudianteEstMatricula = new javax.swing.JLabel();
        TfEstudianteEstMatricula = new javax.swing.JComboBox<>();
        LbEstudianteEstGraduacion = new javax.swing.JLabel();
        TfEstudianteEstGraduacion = new javax.swing.JComboBox<>();
        LbEstudianteCarrera = new javax.swing.JLabel();
        TfEstudianteCarrera = new javax.swing.JTextField();
        PanelPregrado = new javax.swing.JPanel();
        TfPregradoCodigo = new javax.swing.JTextField();
        LbPregradoCodigo = new javax.swing.JLabel();
        LbPregradoNombre = new javax.swing.JLabel();
        TfPregradoNombre = new javax.swing.JTextField();
        LbPregradoFacultad = new javax.swing.JLabel();
        CbPregradoFacultad = new javax.swing.JComboBox<>();
        PanelPosgrado = new javax.swing.JPanel();
        LbPosgradoCodigo = new javax.swing.JLabel();
        TfPosgradoCodigo = new javax.swing.JTextField();
        LbPosgradoNombre = new javax.swing.JLabel();
        TfPosgradoNombre = new javax.swing.JTextField();
        LbPosgradoFacultad = new javax.swing.JLabel();
        CbPosgradoFacultad = new javax.swing.JComboBox<>();
        LbPosgradoTipoEspecialización = new javax.swing.JLabel();
        CbPosgradoTipoEspecialización = new javax.swing.JComboBox<>();

        LbEstudianteNombre2.setText("N. Teléfono");

        TfEstudianteNombre2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TfEstudianteNombre2ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Propiedades - Modificar");
        setIconImage(ClasePrincipal.favicon);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        LbImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finallogica/Interfaz/img/decoadmin.png"))); // NOI18N
        LbImg.setText("LogoAdmin");
        LbImg.setPreferredSize(new java.awt.Dimension(262, 120));

        LbTitulo.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        LbTitulo.setText("Modificar Datos");

        BtCerrar.setText("Cancelar");
        BtCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtCerrarActionPerformed(evt);
            }
        });

        BtAlmacenar.setText("Almacenar");
        BtAlmacenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtAlmacenarActionPerformed(evt);
            }
        });

        LbEstudianteNombre.setText("Nombre:");

        TfEstudianteNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TfEstudianteNombreActionPerformed(evt);
            }
        });

        LbEstudianteApellido.setText("Apellido");

        TfEstudianteApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TfEstudianteApellidoActionPerformed(evt);
            }
        });

        LbEstudianteTipoDocumento.setText("Tipo Documento:");

        TfEstudianteTipoDocumento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TARJETA_IDENTIDAD", "CEDULA_CIUDADANIA" }));
        TfEstudianteTipoDocumento.setSelectedItem(null);

        LbEstudianteNumDocumento.setText("N. Documento:");

        TfEstudianteNumDocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TfEstudianteNumDocumentoActionPerformed(evt);
            }
        });

        LbEstudianteNumTelefono.setText("N. Teléfono:");

        TfEstudianteNumTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TfEstudianteNumTelefonoActionPerformed(evt);
            }
        });

        LbEstudianteEstMatricula.setText("Est. Matricula:");

        TfEstudianteEstMatricula.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ACTIVO", "INACTIVO" }));
        TfEstudianteEstMatricula.setSelectedItem(null);

        LbEstudianteEstGraduacion.setText("Est. Graduación:");

        TfEstudianteEstGraduacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "EGRESADO", "PENDIENTE", "NO_EGRESADO", "GRADUADO" }));
        TfEstudianteEstGraduacion.setSelectedItem(null);

        LbEstudianteCarrera.setText("Carrera:");

        TfEstudianteCarrera.setEditable(false);
        TfEstudianteCarrera.setForeground(new java.awt.Color(98, 98, 98));
        TfEstudianteCarrera.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TfEstudianteCarrera.setText("Click acá para seleccionar...");
        TfEstudianteCarrera.setActionCommand("<Not Set>");
        TfEstudianteCarrera.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TfEstudianteCarreraMouseClicked(evt);
            }
        });
        TfEstudianteCarrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TfEstudianteCarreraActionPerformed(evt);
            }
        });
        TfEstudianteCarrera.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                TfEstudianteCarreraPropertyChange(evt);
            }
        });

        javax.swing.GroupLayout PanelEstudianteLayout = new javax.swing.GroupLayout(PanelEstudiante);
        PanelEstudiante.setLayout(PanelEstudianteLayout);
        PanelEstudianteLayout.setHorizontalGroup(
            PanelEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelEstudianteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(LbEstudianteApellido, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LbEstudianteTipoDocumento, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                    .addComponent(LbEstudianteNumDocumento, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LbEstudianteNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelEstudianteLayout.createSequentialGroup()
                        .addComponent(TfEstudianteApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(LbEstudianteEstMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelEstudianteLayout.createSequentialGroup()
                        .addComponent(TfEstudianteNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(LbEstudianteNumTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelEstudianteLayout.createSequentialGroup()
                        .addComponent(TfEstudianteTipoDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(LbEstudianteEstGraduacion, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelEstudianteLayout.createSequentialGroup()
                        .addComponent(TfEstudianteNumDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(LbEstudianteCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31)
                .addGroup(PanelEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TfEstudianteEstMatricula, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TfEstudianteEstGraduacion, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TfEstudianteCarrera, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                    .addComponent(TfEstudianteNumTelefono))
                .addContainerGap())
        );
        PanelEstudianteLayout.setVerticalGroup(
            PanelEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelEstudianteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TfEstudianteNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LbEstudianteNombre)
                    .addComponent(LbEstudianteNumTelefono)
                    .addComponent(TfEstudianteNumTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TfEstudianteApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LbEstudianteApellido)
                    .addComponent(LbEstudianteEstMatricula)
                    .addComponent(TfEstudianteEstMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbEstudianteTipoDocumento)
                    .addComponent(TfEstudianteTipoDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LbEstudianteEstGraduacion)
                    .addComponent(TfEstudianteEstGraduacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TfEstudianteNumDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LbEstudianteNumDocumento)
                    .addComponent(LbEstudianteCarrera)
                    .addComponent(TfEstudianteCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TpTipo.addTab("Estudiante", PanelEstudiante);

        TfPregradoCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TfPregradoCodigoActionPerformed(evt);
            }
        });

        LbPregradoCodigo.setText("Código:");

        LbPregradoNombre.setText("Nombre:");

        TfPregradoNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TfPregradoNombreActionPerformed(evt);
            }
        });

        LbPregradoFacultad.setText("Facultad:");

        CbPregradoFacultad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CIENCIAS_POLITICAS_JURIDICAS", "CIENCIAS_EMPRESARIALES", "CIENCIAS_HUMANAS_ED", "INGENIERIAS" }));
        CbPregradoFacultad.setSelectedItem(null);

        javax.swing.GroupLayout PanelPregradoLayout = new javax.swing.GroupLayout(PanelPregrado);
        PanelPregrado.setLayout(PanelPregradoLayout);
        PanelPregradoLayout.setHorizontalGroup(
            PanelPregradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPregradoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelPregradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PanelPregradoLayout.createSequentialGroup()
                        .addComponent(LbPregradoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TfPregradoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelPregradoLayout.createSequentialGroup()
                        .addGroup(PanelPregradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LbPregradoFacultad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(PanelPregradoLayout.createSequentialGroup()
                                .addComponent(LbPregradoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 7, Short.MAX_VALUE)))
                        .addGroup(PanelPregradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelPregradoLayout.createSequentialGroup()
                                .addGap(197, 197, 197)
                                .addComponent(TfPregradoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelPregradoLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CbPregradoFacultad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(274, Short.MAX_VALUE))
        );
        PanelPregradoLayout.setVerticalGroup(
            PanelPregradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPregradoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelPregradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TfPregradoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LbPregradoCodigo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelPregradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TfPregradoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LbPregradoNombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelPregradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbPregradoFacultad)
                    .addComponent(CbPregradoFacultad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        TpTipo.addTab("Pregrado", PanelPregrado);

        LbPosgradoCodigo.setText("Código:");

        TfPosgradoCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TfPosgradoCodigoActionPerformed(evt);
            }
        });

        LbPosgradoNombre.setText("Nombre:");

        TfPosgradoNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TfPosgradoNombreActionPerformed(evt);
            }
        });

        LbPosgradoFacultad.setText("Facultad:");

        CbPosgradoFacultad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CIENCIAS_POLITICAS_JURIDICAS", "CIENCIAS_EMPRESARIALES", "CIENCIAS_HUMANAS_ED", "INGENIERIAS" }));
        CbPosgradoFacultad.setSelectedItem(null);

        LbPosgradoTipoEspecialización.setText("Tipo Especialización:");

        CbPosgradoTipoEspecialización.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MAESTRIA", "ESPECIALIZACION" }));
        CbPosgradoTipoEspecialización.setSelectedItem(null);

        javax.swing.GroupLayout PanelPosgradoLayout = new javax.swing.GroupLayout(PanelPosgrado);
        PanelPosgrado.setLayout(PanelPosgradoLayout);
        PanelPosgradoLayout.setHorizontalGroup(
            PanelPosgradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPosgradoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelPosgradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelPosgradoLayout.createSequentialGroup()
                        .addComponent(LbPosgradoCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(80, 80, 80)
                        .addComponent(TfPosgradoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelPosgradoLayout.createSequentialGroup()
                        .addComponent(LbPosgradoNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TfPosgradoNombre))
                    .addGroup(PanelPosgradoLayout.createSequentialGroup()
                        .addGroup(PanelPosgradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LbPosgradoFacultad, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                            .addComponent(LbPosgradoTipoEspecialización, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelPosgradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(CbPosgradoFacultad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CbPosgradoTipoEspecialización, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(279, 279, 279))
        );
        PanelPosgradoLayout.setVerticalGroup(
            PanelPosgradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPosgradoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelPosgradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TfPosgradoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LbPosgradoCodigo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelPosgradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TfPosgradoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LbPosgradoNombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelPosgradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbPosgradoFacultad)
                    .addComponent(CbPosgradoFacultad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelPosgradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbPosgradoTipoEspecialización)
                    .addComponent(CbPosgradoTipoEspecialización, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        TpTipo.addTab("Posgrado", PanelPosgrado);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(TpTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LbTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
                        .addGap(149, 149, 149)
                        .addComponent(LbImg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BtAlmacenar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtCerrar))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LbImg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(LbTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TpTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtAlmacenar)
                    .addComponent(BtCerrar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtCerrarActionPerformed
        this.dispose();
    }//GEN-LAST:event_BtCerrarActionPerformed

    private void TfEstudianteNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TfEstudianteNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TfEstudianteNombreActionPerformed

    private void TfEstudianteApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TfEstudianteApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TfEstudianteApellidoActionPerformed

    private void TfEstudianteNumDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TfEstudianteNumDocumentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TfEstudianteNumDocumentoActionPerformed

    private void TfEstudianteNumTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TfEstudianteNumTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TfEstudianteNumTelefonoActionPerformed

    private void TfEstudianteNombre2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TfEstudianteNombre2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TfEstudianteNombre2ActionPerformed

    private void TfEstudianteCarreraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TfEstudianteCarreraMouseClicked
         registroPrePos.setVisible(true);
        registroPrePos.addComponentListener(new ComponentAdapter() {
            @Override
            public void componentHidden(ComponentEvent e) {
                TfEstudianteCarrera.setText(String.valueOf(registroPrePos.selected));
                 registroPrePos.dispose();
            }
        });
                
    
    }//GEN-LAST:event_TfEstudianteCarreraMouseClicked

    private void TfEstudianteCarreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TfEstudianteCarreraActionPerformed
  
    }//GEN-LAST:event_TfEstudianteCarreraActionPerformed

    private void TfEstudianteCarreraPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_TfEstudianteCarreraPropertyChange
       
    }//GEN-LAST:event_TfEstudianteCarreraPropertyChange

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        
        
    }//GEN-LAST:event_formWindowGainedFocus

    private void BtAlmacenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtAlmacenarActionPerformed
           switch (index) {
               // Si se está llenando un campo de estudiante. hay dos cosas que pueden
               // pasar: 1. Esté agregando (primer if) o esté modificando (else)
            case 0:
            // Comprueba si los datos están bien & que no hayan datos en la clase.
            if ((data == null) && (comprobarAdicion(this.index))) {
                // Se crea un objeto estudiante, no sabemos si tiene un pregrado
                // o posgrado en su constructor.
                Object estudiante = null;
                // Se comprueba si la carrera a agregar tiene instancia en pregrado.
                // si tiene, se crea con pregrado, si no, por omisión se toma posgrado.
                if (Pregrado.class.isInstance(Operaciones.buscarCarrera(Integer.parseInt(TfEstudianteCarrera.getText())))) {
                    estudiante = new Estudiante(TfEstudianteNombre.getText(),TfEstudianteApellido.getText(),
                    Estudiante.tipo_documento.valueOf(TfEstudianteTipoDocumento.getItemAt(TfEstudianteTipoDocumento.getSelectedIndex())),
                    TfEstudianteNumDocumento.getText(), TfEstudianteNumTelefono.getText(), Pregrado.class.cast(Operaciones.buscarCarrera(Integer.parseInt(TfEstudianteCarrera.getText()))),
                    Estudiante.estado_matricula.valueOf(TfEstudianteEstMatricula.getItemAt(TfEstudianteEstMatricula.getSelectedIndex())),
                    Estudiante.estado_graduacion.valueOf(TfEstudianteEstGraduacion.getItemAt(TfEstudianteEstGraduacion.getSelectedIndex())));
            }   else {
                    estudiante = new Estudiante(TfEstudianteNombre.getText(),TfEstudianteApellido.getText(),
                    Estudiante.tipo_documento.valueOf(TfEstudianteTipoDocumento.getItemAt(TfEstudianteTipoDocumento.getSelectedIndex())),
                    TfEstudianteNumDocumento.getText(), TfEstudianteNumTelefono.getText(), Posgrado.class.cast(Operaciones.buscarCarrera(Integer.parseInt(TfEstudianteCarrera.getText()))),
                    Estudiante.estado_matricula.valueOf(TfEstudianteEstMatricula.getItemAt(TfEstudianteEstMatricula.getSelectedIndex())),
                    Estudiante.estado_graduacion.valueOf(TfEstudianteEstGraduacion.getItemAt(TfEstudianteEstGraduacion.getSelectedIndex())));
                }
                Operaciones.agregarRegistro(estudiante);
                Operaciones.actualizarBasesDeDatos();
                this.setVisible(false);
            } else {
                // Modifica datos ya existentes de un estudiante.
                    Estudiante e = Estudiante.class.cast(data);
                    // Se miran los campos modificados
                    if (TfEstudianteNombre.getText().trim().length() != 0 ){e.setNombre(TfEstudianteNombre.getText());}
                    if (TfEstudianteApellido.getText().trim().length() != 0 ){e.setApellido(TfEstudianteApellido.getText());}
                    if ((TfEstudianteNumDocumento.getText().trim().length() != 0) && (Operaciones.isInteger(TfEstudianteNumDocumento.getText()))){e.setNumero_documento(TfEstudianteNumDocumento.getText());}
                    if ((TfEstudianteNumTelefono.getText().trim().length() != 0) && (Operaciones.isInteger(TfEstudianteNumTelefono.getText()))){e.setNumero_telefono(TfEstudianteNumTelefono.getText());}
                    if (TfEstudianteTipoDocumento.getSelectedIndex() >= 0){e.setTipo_documento(Estudiante.tipo_documento.valueOf(TfEstudianteTipoDocumento.getItemAt(TfEstudianteTipoDocumento.getSelectedIndex())));}
                    if (TfEstudianteEstMatricula.getSelectedIndex() >= 0){e.setEstado_matricula(Estudiante.estado_matricula.valueOf(TfEstudianteEstMatricula.getItemAt(TfEstudianteEstMatricula.getSelectedIndex())));}
                    if (TfEstudianteEstGraduacion.getSelectedIndex() >= 0){e.setEstado_graduacion(Estudiante.estado_graduacion.valueOf(TfEstudianteEstGraduacion.getItemAt(TfEstudianteEstGraduacion.getSelectedIndex())));}
                    if ((Operaciones.isInteger(TfEstudianteCarrera.getText()))) {e.setCarrera(Carrera.class.cast(Operaciones.buscarCarrera(Integer.parseInt(TfEstudianteCarrera.getText()))));}
                    // Se regenera el código, ya que cambia cuando se cambian ciertos campos
                    e.regenerarCodigo();
                    // Se asigna el estudiante modificado en el lugar del estudiante sin modificar
                    ClasePrincipal.estudiante.set(data_index, e);
                    this.setVisible(false);
                
            }
                break;
            case 2:
                if ((data == null) && (comprobarAdicion(index))) {
                    Operaciones.agregarRegistro(new Pregrado(Integer.parseInt(TfPregradoCodigo.getText()), 
                    TfPregradoNombre.getText(), Carrera.facultades.valueOf(CbPregradoFacultad.getItemAt(CbPregradoFacultad.getSelectedIndex()))));
                    Operaciones.actualizarBasesDeDatos();
                    this.setVisible(false);
                } else {
                    // Pregrado p = Pregrado.class.cast(data);
                    // if ((TfPregradoCodigo.getText().trim().length() != 0) && (Operaciones.isInteger(TfPregradoCodigo.getText()))) {p.setCodigo(Integer.parseInt(TfPregradoCodigo.getText()));}
                    // if ((TfPregradoNombre.getText().trim().length() != 0)) {p.setNombre(TfPregradoNombre.getText());}
                    JOptionPane.showMessageDialog(null, "La modificación de carreras está deshabilitada, ya que puede incurrir en estudiantes con carreras inválidas.", "Información", JOptionPane.INFORMATION_MESSAGE);
                }
                break;
            case 3:
                if ((data == null) && (comprobarAdicion(index))) {
                    Operaciones.agregarRegistro(new Posgrado(Integer.parseInt(TfPosgradoCodigo.getText()), 
                    TfPosgradoNombre.getText(),
                    Posgrado.tipo.valueOf(CbPosgradoTipoEspecialización.getItemAt(CbPosgradoTipoEspecialización.getSelectedIndex())),
                    Posgrado.facultades.valueOf(CbPosgradoFacultad.getItemAt(CbPosgradoFacultad.getSelectedIndex()))));
                    Operaciones.actualizarBasesDeDatos();
                    this.setVisible(false);
                }
                else {
                        JOptionPane.showMessageDialog(null, "La modificación de carreras está deshabilitada, ya que puede incurrir en estudiantes con carreras inválidas.", "Información", JOptionPane.INFORMATION_MESSAGE);
                        }
           }
    }//GEN-LAST:event_BtAlmacenarActionPerformed

    private void TfPregradoCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TfPregradoCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TfPregradoCodigoActionPerformed

    private void TfPregradoNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TfPregradoNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TfPregradoNombreActionPerformed

    private void TfPosgradoNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TfPosgradoNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TfPosgradoNombreActionPerformed

    private void TfPosgradoCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TfPosgradoCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TfPosgradoCodigoActionPerformed
    private boolean comprobarAdicion(int index){
        boolean check = true;
        switch(index) {
            /* Comprueba que los campos sean válidos, funciona de esta manera:
            
            1. Comprueba que ningun campo este vacio, y que tenga un valor valido.
            2. Comprueba que el tipo de dato sea el correcto, y que no hayan conflictos.
            
            */ 
            case 0:
                check &=(TfEstudianteNombre.getText().trim().length() != 0 );
                check &=(TfEstudianteApellido.getText().trim().length() != 0 );
                check &=(TfEstudianteTipoDocumento.getSelectedIndex() >= 0 );
                check &=(TfEstudianteNumDocumento.getText().trim().length() != 0 );
                check &=(TfEstudianteNumTelefono.getText().trim().length() != 0 );
                check &=(TfEstudianteEstMatricula.getSelectedIndex() >= 0);
                check &=(TfEstudianteEstGraduacion.getSelectedIndex() >= 0 );
                check &=(Operaciones.isInteger(TfEstudianteCarrera.getText()));
                if (check) {
                check &=(Operaciones.isInteger(TfEstudianteNumDocumento.getText()));
                check &=(Operaciones.isInteger(TfEstudianteNumTelefono.getText()));
                if (check) {
                    return true;
                } else {
                    JOptionPane.showMessageDialog(null, "No se ha guardado el estudiante. Revise el número de teléfono o el número de documento sean válidos.", "Error al guardar", JOptionPane.ERROR_MESSAGE);
                
                }
            } else {
                    JOptionPane.showMessageDialog(null, "No se ha guardado el estudiante. Revise que todos los campos esten llenos y sean validos, e inténtelo de nuevo.", "Error al guardar", JOptionPane.ERROR_MESSAGE);
                
                }
                break;
            case 2:
                // Pregrados, comprobar campos para añadir pregrado: IWP
                check &=(TfPregradoCodigo.getText().trim().length() != 0);
                check &=(TfPregradoNombre.getText().trim().length() != 0);
                check &=(CbPregradoFacultad.getSelectedIndex() >= 0);
                if (check) {
                    check &=(Operaciones.isInteger(TfPregradoCodigo.getText()));
                    if (check) {
                        return true;
                    } else {
                        JOptionPane.showMessageDialog(null, "No se ha guardado el pregrado. Revise que el código sea numérico e inténtelo de nuevo.", "Error al guardar", JOptionPane.ERROR_MESSAGE);
                
                    } 
                } else {
                    JOptionPane.showMessageDialog(null, "No se ha guardado el pregrado. Revise que no hayan campos vacios e inténtelo de nuevo.", "Error al guardar", JOptionPane.ERROR_MESSAGE);
                
                }
                break;
            case 3:
                // Posgrados, comprobar campos para añadir posgrado: IWP
                check &=(TfPosgradoCodigo.getText().trim().length() != 0);
                check &=(TfPosgradoNombre.getText().trim().length() != 0);
                check &=(CbPosgradoFacultad.getSelectedIndex() >= 0);
                check &=(CbPosgradoTipoEspecialización.getSelectedIndex() >= 0);
                if (check) {
                    check &=(Operaciones.isInteger(TfPosgradoCodigo.getText()));
                    if (check) {
                        return true;
                    } else {
                        JOptionPane.showMessageDialog(null, "No se ha guardado el posgrado. Revise que el código sea numérico e inténtelo de nuevo.", "Error al guardar", JOptionPane.ERROR_MESSAGE);
                
                    } 
                } else {
                    JOptionPane.showMessageDialog(null, "No se ha guardado el posgrado. Revise que no hayan campos vacios e inténtelo de nuevo.", "Error al guardar", JOptionPane.ERROR_MESSAGE);
                
                }
                break;
            default:
                System.out.println("Asistente.comprobar: Indice de lista no valido : " + index);
        }
        return false;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Asistente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Asistente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Asistente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Asistente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Asistente(0, null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtAlmacenar;
    private javax.swing.JButton BtCerrar;
    private javax.swing.JComboBox<String> CbPosgradoFacultad;
    private javax.swing.JComboBox<String> CbPosgradoTipoEspecialización;
    private javax.swing.JComboBox<String> CbPregradoFacultad;
    private javax.swing.JLabel LbEstudianteApellido;
    private javax.swing.JLabel LbEstudianteCarrera;
    private javax.swing.JLabel LbEstudianteEstGraduacion;
    private javax.swing.JLabel LbEstudianteEstMatricula;
    private javax.swing.JLabel LbEstudianteNombre;
    private javax.swing.JLabel LbEstudianteNombre2;
    private javax.swing.JLabel LbEstudianteNumDocumento;
    private javax.swing.JLabel LbEstudianteNumTelefono;
    private javax.swing.JLabel LbEstudianteTipoDocumento;
    private javax.swing.JLabel LbImg;
    private javax.swing.JLabel LbPosgradoCodigo;
    private javax.swing.JLabel LbPosgradoFacultad;
    private javax.swing.JLabel LbPosgradoNombre;
    private javax.swing.JLabel LbPosgradoTipoEspecialización;
    private javax.swing.JLabel LbPregradoCodigo;
    private javax.swing.JLabel LbPregradoFacultad;
    private javax.swing.JLabel LbPregradoNombre;
    private javax.swing.JLabel LbTitulo;
    private javax.swing.JPanel PanelEstudiante;
    private javax.swing.JPanel PanelPosgrado;
    private javax.swing.JPanel PanelPregrado;
    private javax.swing.JTextField TfEstudianteApellido;
    private javax.swing.JTextField TfEstudianteCarrera;
    private javax.swing.JComboBox<String> TfEstudianteEstGraduacion;
    private javax.swing.JComboBox<String> TfEstudianteEstMatricula;
    private javax.swing.JTextField TfEstudianteNombre;
    private javax.swing.JTextField TfEstudianteNombre2;
    private javax.swing.JTextField TfEstudianteNumDocumento;
    private javax.swing.JTextField TfEstudianteNumTelefono;
    private javax.swing.JComboBox<String> TfEstudianteTipoDocumento;
    private javax.swing.JTextField TfPosgradoCodigo;
    private javax.swing.JTextField TfPosgradoNombre;
    private javax.swing.JTextField TfPregradoCodigo;
    private javax.swing.JTextField TfPregradoNombre;
    private javax.swing.JTabbedPane TpTipo;
    // End of variables declaration//GEN-END:variables
}
