    /*
 * 
 */
package finallogica.Interfaz.Registros;

import finallogica.Clases.Estudiante;
import finallogica.Clases.Fijas.Posgrado;
import finallogica.Clases.Fijas.Pregrado;
import finallogica.Interfaz.ClasePrincipal;
import finallogica.Modelo.Operaciones;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import java.awt.event.WindowEvent;
import java.awt.event.WindowStateListener;
import javax.swing.JOptionPane;

/**
 *
 * @author AntJZ
 */
public class Asistente extends javax.swing.JFrame {
    private static SeleccionarRegistroPrePos registroPrePos = new SeleccionarRegistroPrePos();
    Object data;
    int index; 
    /**
     *  ASISTENTE.
     * Esta clase crea una nueva entrada, dependiendo del tipo de dato.
     * @param index Recibe el índice de la lista [Estudiante, TrabajoDeGrado, Pregrado, Posgrado]
     * 
     * @data recibe un dato, y el programa reconoce si es un estudiante
     *        o carrera.
     * @index se recibe si no se va a modificar un dato, sino que solamente
     *        lo agrega.
     * 
     */
     public Asistente(int index) {
        initComponents();
        LbTitulo.setText("Agregar Datos");
        // Averiguar que tipo de dato es
        switch (index) {
            case 0:
                // Estudiantes
                // Limpieza
        TfEstudianteTipoDocumento.setSelectedItem(null);
        TfEstudianteEstGraduacion.setSelectedItem(null);
        TfEstudianteEstMatricula.setSelectedItem(null);
        TfEstudianteCarrera.setText("Click acá para seleccionar...");
                // Se esconden los otros combos.
                TpTipo.remove(PanelPosgrado);
                TpTipo.remove(PanelPregrado);
                break;
            case 1:
                // Trabajos de grado
                TpTipo.remove(PanelPosgrado);
                TpTipo.remove(PanelEstudiante);
                TpTipo.remove(PanelPregrado);
                break;
            case 2:
                // Pregrados
                TpTipo.remove(PanelPosgrado);
                TpTipo.remove(PanelEstudiante);
                break;
            case 3:
                // Posgrados
                TpTipo.remove(PanelEstudiante);
                TpTipo.remove(PanelPregrado);
                break;
            default:
                JOptionPane.showMessageDialog(null, "Corre el programa desde la clase principal, ya que no se han cargado aún los datos...");
                this.dispose();
        }
    }
    
    public Asistente(Object data) {
        this.data = data;
        initComponents();
        // Averiguar que tipo de dato es
        index = Operaciones.buscarIndice(data);
        switch (Operaciones.buscarTipo(data)) {
            case 0:
                // Estudiantes
                TpTipo.remove(PanelPosgrado);
                TpTipo.remove(PanelPregrado);
                break;
            case 1:
                // Trabajos de grado
                TpTipo.remove(PanelPosgrado);
                TpTipo.remove(PanelPregrado);
                TpTipo.remove(PanelEstudiante);
                break;
            case 2:
                // Pregrados
                TpTipo.remove(PanelPosgrado);
                TpTipo.remove(PanelEstudiante);
                break;
            case 3:
                // Posgrados
                TpTipo.remove(PanelEstudiante);
                TpTipo.remove(PanelPregrado);
                break;
            default:
                JOptionPane.showMessageDialog(null, "Corre el programa desde la clase principal, ya que no se han cargado aún los datos...");
                this.dispose();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LbEstudianteNombre2 = new javax.swing.JLabel();
        TfEstudianteNombre2 = new javax.swing.JTextField();
        LbImg = new javax.swing.JLabel();
        LbTitulo = new javax.swing.JLabel();
        BtCerrar = new javax.swing.JButton();
        BtAlmacenar = new javax.swing.JButton();
        TpTipo = new javax.swing.JTabbedPane();
        PanelEstudiante = new javax.swing.JPanel();
        LbEstudianteNombre = new javax.swing.JLabel();
        TfEstudianteNombre = new javax.swing.JTextField();
        LbEstudianteApellido = new javax.swing.JLabel();
        TfEstudianteApellido = new javax.swing.JTextField();
        LbEstudianteTipoDocumento = new javax.swing.JLabel();
        TfEstudianteTipoDocumento = new javax.swing.JComboBox<>();
        LbEstudianteNumDocumento = new javax.swing.JLabel();
        TfEstudianteNumDocumento = new javax.swing.JTextField();
        LbEstudianteNumTelefono = new javax.swing.JLabel();
        TfEstudianteNumTelefono = new javax.swing.JTextField();
        LbEstudianteEstMatricula = new javax.swing.JLabel();
        TfEstudianteEstMatricula = new javax.swing.JComboBox<>();
        LbEstudianteEstGraduacion = new javax.swing.JLabel();
        TfEstudianteEstGraduacion = new javax.swing.JComboBox<>();
        LbEstudianteCarrera = new javax.swing.JLabel();
        TfEstudianteCarrera = new javax.swing.JTextField();
        PanelPregrado = new javax.swing.JPanel();
        PanelPosgrado = new javax.swing.JPanel();

        LbEstudianteNombre2.setText("N. Teléfono");

        TfEstudianteNombre2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TfEstudianteNombre2ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Propiedades - Modificar");
        setIconImage(ClasePrincipal.favicon);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        LbImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finallogica/Interfaz/img/decoadmin.png"))); // NOI18N
        LbImg.setText("LogoAdmin");
        LbImg.setPreferredSize(new java.awt.Dimension(262, 120));

        LbTitulo.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        LbTitulo.setText("Modificar Datos");

        BtCerrar.setText("Cancelar");
        BtCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtCerrarActionPerformed(evt);
            }
        });

        BtAlmacenar.setText("Almacenar");
        BtAlmacenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtAlmacenarActionPerformed(evt);
            }
        });

        LbEstudianteNombre.setText("Nombre:");

        TfEstudianteNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TfEstudianteNombreActionPerformed(evt);
            }
        });

        LbEstudianteApellido.setText("Apellido");

        TfEstudianteApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TfEstudianteApellidoActionPerformed(evt);
            }
        });

        LbEstudianteTipoDocumento.setText("Tipo Documento:");

        TfEstudianteTipoDocumento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TARJETA_IDENTIDAD", "CEDULA_CIUDADANIA" }));
        TfEstudianteTipoDocumento.setSelectedItem(null);

        LbEstudianteNumDocumento.setText("N. Documento:");

        TfEstudianteNumDocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TfEstudianteNumDocumentoActionPerformed(evt);
            }
        });

        LbEstudianteNumTelefono.setText("N. Teléfono:");

        TfEstudianteNumTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TfEstudianteNumTelefonoActionPerformed(evt);
            }
        });

        LbEstudianteEstMatricula.setText("Est. Matricula:");

        TfEstudianteEstMatricula.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ACTIVO", "INACTIVO" }));
        TfEstudianteEstMatricula.setSelectedItem(null);

        LbEstudianteEstGraduacion.setText("Est. Graduación:");

        TfEstudianteEstGraduacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "EGRESADO", "PENDIENTE", "NO_EGRESADO", "GRADUADO" }));
        TfEstudianteEstGraduacion.setSelectedItem(null);

        LbEstudianteCarrera.setText("Carrera:");

        TfEstudianteCarrera.setEditable(false);
        TfEstudianteCarrera.setForeground(new java.awt.Color(98, 98, 98));
        TfEstudianteCarrera.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TfEstudianteCarrera.setText("Click acá para seleccionar...");
        TfEstudianteCarrera.setActionCommand("<Not Set>");
        TfEstudianteCarrera.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TfEstudianteCarreraMouseClicked(evt);
            }
        });
        TfEstudianteCarrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TfEstudianteCarreraActionPerformed(evt);
            }
        });
        TfEstudianteCarrera.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                TfEstudianteCarreraPropertyChange(evt);
            }
        });

        javax.swing.GroupLayout PanelEstudianteLayout = new javax.swing.GroupLayout(PanelEstudiante);
        PanelEstudiante.setLayout(PanelEstudianteLayout);
        PanelEstudianteLayout.setHorizontalGroup(
            PanelEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelEstudianteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(LbEstudianteApellido, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LbEstudianteTipoDocumento, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                    .addComponent(LbEstudianteNumDocumento, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LbEstudianteNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelEstudianteLayout.createSequentialGroup()
                        .addComponent(TfEstudianteApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(LbEstudianteEstMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelEstudianteLayout.createSequentialGroup()
                        .addComponent(TfEstudianteNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(LbEstudianteNumTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelEstudianteLayout.createSequentialGroup()
                        .addComponent(TfEstudianteTipoDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(LbEstudianteEstGraduacion, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelEstudianteLayout.createSequentialGroup()
                        .addComponent(TfEstudianteNumDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(LbEstudianteCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31)
                .addGroup(PanelEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TfEstudianteEstMatricula, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TfEstudianteEstGraduacion, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TfEstudianteCarrera, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                    .addComponent(TfEstudianteNumTelefono))
                .addContainerGap())
        );
        PanelEstudianteLayout.setVerticalGroup(
            PanelEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelEstudianteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TfEstudianteNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LbEstudianteNombre)
                    .addComponent(LbEstudianteNumTelefono)
                    .addComponent(TfEstudianteNumTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TfEstudianteApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LbEstudianteApellido)
                    .addComponent(LbEstudianteEstMatricula)
                    .addComponent(TfEstudianteEstMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbEstudianteTipoDocumento)
                    .addComponent(TfEstudianteTipoDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LbEstudianteEstGraduacion)
                    .addComponent(TfEstudianteEstGraduacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TfEstudianteNumDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LbEstudianteNumDocumento)
                    .addComponent(LbEstudianteCarrera)
                    .addComponent(TfEstudianteCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TpTipo.addTab("Estudiante", PanelEstudiante);

        javax.swing.GroupLayout PanelPregradoLayout = new javax.swing.GroupLayout(PanelPregrado);
        PanelPregrado.setLayout(PanelPregradoLayout);
        PanelPregradoLayout.setHorizontalGroup(
            PanelPregradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 607, Short.MAX_VALUE)
        );
        PanelPregradoLayout.setVerticalGroup(
            PanelPregradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 153, Short.MAX_VALUE)
        );

        TpTipo.addTab("Pregrado", PanelPregrado);

        javax.swing.GroupLayout PanelPosgradoLayout = new javax.swing.GroupLayout(PanelPosgrado);
        PanelPosgrado.setLayout(PanelPosgradoLayout);
        PanelPosgradoLayout.setHorizontalGroup(
            PanelPosgradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 607, Short.MAX_VALUE)
        );
        PanelPosgradoLayout.setVerticalGroup(
            PanelPosgradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 153, Short.MAX_VALUE)
        );

        TpTipo.addTab("Posgrado", PanelPosgrado);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LbTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(149, 149, 149)
                        .addComponent(LbImg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BtAlmacenar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BtCerrar))
                            .addComponent(TpTipo, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LbImg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(LbTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TpTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtAlmacenar)
                    .addComponent(BtCerrar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtCerrarActionPerformed
        this.dispose();
    }//GEN-LAST:event_BtCerrarActionPerformed

    private void TfEstudianteNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TfEstudianteNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TfEstudianteNombreActionPerformed

    private void TfEstudianteApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TfEstudianteApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TfEstudianteApellidoActionPerformed

    private void TfEstudianteNumDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TfEstudianteNumDocumentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TfEstudianteNumDocumentoActionPerformed

    private void TfEstudianteNumTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TfEstudianteNumTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TfEstudianteNumTelefonoActionPerformed

    private void TfEstudianteNombre2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TfEstudianteNombre2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TfEstudianteNombre2ActionPerformed

    private void TfEstudianteCarreraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TfEstudianteCarreraMouseClicked
         registroPrePos.setVisible(true);
        registroPrePos.addComponentListener(new ComponentAdapter() {
            @Override
            public void componentHidden(ComponentEvent e) {
                TfEstudianteCarrera.setText(String.valueOf(registroPrePos.selected));
                 registroPrePos.dispose();
            }
        });
                
    
    }//GEN-LAST:event_TfEstudianteCarreraMouseClicked

    private void TfEstudianteCarreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TfEstudianteCarreraActionPerformed
  
    }//GEN-LAST:event_TfEstudianteCarreraActionPerformed

    private void TfEstudianteCarreraPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_TfEstudianteCarreraPropertyChange
       
    }//GEN-LAST:event_TfEstudianteCarreraPropertyChange

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        
        
    }//GEN-LAST:event_formWindowGainedFocus

    private void BtAlmacenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtAlmacenarActionPerformed
        if ((data == null) && (comprobarAdicion(index))) {
            Object estudiante = null;
                if (Pregrado.class.isInstance(Operaciones.buscarCarrera(Integer.parseInt(TfEstudianteCarrera.getText())))) {
            estudiante = new Estudiante(TfEstudianteNombre.getText(),TfEstudianteApellido.getText(),
            Estudiante.tipo_documento.valueOf(TfEstudianteTipoDocumento.getItemAt(TfEstudianteTipoDocumento.getSelectedIndex())),
            TfEstudianteNumDocumento.getText(), TfEstudianteNumTelefono.getText(), Pregrado.class.cast(Operaciones.buscarCarrera(Integer.parseInt(TfEstudianteCarrera.getText()))),
            Estudiante.estado_matricula.valueOf(TfEstudianteEstMatricula.getItemAt(TfEstudianteEstMatricula.getSelectedIndex())),
            Estudiante.estado_graduacion.valueOf(TfEstudianteEstGraduacion.getItemAt(TfEstudianteEstGraduacion.getSelectedIndex())));
            }else {
            estudiante = new Estudiante(TfEstudianteNombre.getText(),TfEstudianteApellido.getText(),
            Estudiante.tipo_documento.valueOf(TfEstudianteTipoDocumento.getItemAt(TfEstudianteTipoDocumento.getSelectedIndex())),
            TfEstudianteNumDocumento.getText(), TfEstudianteNumTelefono.getText(), Posgrado.class.cast(Operaciones.buscarCarrera(Integer.parseInt(TfEstudianteCarrera.getText()))),
            Estudiante.estado_matricula.valueOf(TfEstudianteEstMatricula.getItemAt(TfEstudianteEstMatricula.getSelectedIndex())),
            Estudiante.estado_graduacion.valueOf(TfEstudianteEstGraduacion.getItemAt(TfEstudianteEstGraduacion.getSelectedIndex())));
                }
            Operaciones.agregarEstudiante(estudiante);
            Operaciones.actualizarBasesDeDatos();
            this.setVisible(false);
        } else {
            
        }
    }//GEN-LAST:event_BtAlmacenarActionPerformed
    private boolean comprobarAdicion(int index){
        boolean check = true;
        switch (index) {
            /* Comprueba que los campos sean válidos, funciona de esta manera:
            
            1. Comprueba que ningun campo este vacio, y que tenga un valor valido.
            2. Comprueba que el tipo de dato sea el correcto, y que no hayan conflictos.
            
            */ 
            case 0:
                check &=(TfEstudianteNombre.getText().trim().length() != 0 );
                check &=(TfEstudianteApellido.getText().trim().length() != 0 );
                check &=(TfEstudianteTipoDocumento.getSelectedIndex() >= 0 );
                check &=(TfEstudianteNumDocumento.getText().trim().length() != 0 );
                check &=(TfEstudianteNumTelefono.getText().trim().length() != 0 );
                check &=(TfEstudianteEstMatricula.getSelectedIndex() >= 0);
                check &=(TfEstudianteEstGraduacion.getSelectedIndex() >= 0 );
                check &=(Operaciones.isInteger(TfEstudianteCarrera.getText()));
                if (check) {
                check &=(Operaciones.isInteger(TfEstudianteNumDocumento.getText()));
                check &=(Operaciones.isInteger(TfEstudianteNumTelefono.getText()));
                if (check) {
                    return true;
                } else {
                    JOptionPane.showMessageDialog(null, "No se ha guardado el estudiante. Revise el número de teléfono o el número de documento sean válidos.", "Error al guardar", JOptionPane.ERROR_MESSAGE);
                
                }
            } else {
                    JOptionPane.showMessageDialog(null, "No se ha guardado el estudiante. Revise que todos los campos esten llenos y sean validos, e intentelo de nuevo.", "Error al guardar", JOptionPane.ERROR_MESSAGE);
                
                }
                break;
            default:
                System.out.println("Asistente.comprobar: Indice de lista no valido : " + index);
        }
        return false;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Asistente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Asistente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Asistente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Asistente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Asistente(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtAlmacenar;
    private javax.swing.JButton BtCerrar;
    private javax.swing.JLabel LbEstudianteApellido;
    private javax.swing.JLabel LbEstudianteCarrera;
    private javax.swing.JLabel LbEstudianteEstGraduacion;
    private javax.swing.JLabel LbEstudianteEstMatricula;
    private javax.swing.JLabel LbEstudianteNombre;
    private javax.swing.JLabel LbEstudianteNombre2;
    private javax.swing.JLabel LbEstudianteNumDocumento;
    private javax.swing.JLabel LbEstudianteNumTelefono;
    private javax.swing.JLabel LbEstudianteTipoDocumento;
    private javax.swing.JLabel LbImg;
    private javax.swing.JLabel LbTitulo;
    private javax.swing.JPanel PanelEstudiante;
    private javax.swing.JPanel PanelPosgrado;
    private javax.swing.JPanel PanelPregrado;
    private javax.swing.JTextField TfEstudianteApellido;
    private javax.swing.JTextField TfEstudianteCarrera;
    private javax.swing.JComboBox<String> TfEstudianteEstGraduacion;
    private javax.swing.JComboBox<String> TfEstudianteEstMatricula;
    private javax.swing.JTextField TfEstudianteNombre;
    private javax.swing.JTextField TfEstudianteNombre2;
    private javax.swing.JTextField TfEstudianteNumDocumento;
    private javax.swing.JTextField TfEstudianteNumTelefono;
    private javax.swing.JComboBox<String> TfEstudianteTipoDocumento;
    private javax.swing.JTabbedPane TpTipo;
    // End of variables declaration//GEN-END:variables
}
