/*
 * 
 */
package finallogica.Interfaz.Registros;

import finallogica.Interfaz.ClasePrincipal;
import finallogica.Interfaz.Modelos.Mod_Estudiante;
import finallogica.Interfaz.Modelos.Mod_Posgrado;
import finallogica.Interfaz.Modelos.Mod_Pregrado;
import finallogica.Modelo.Operaciones;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author AntJZ
 */
public class TablaRegistros extends javax.swing.JFrame {
    private int tb_indice;
    public String tipo;
 
    public TablaRegistros() {
        initComponents();
        BtSeleccionar.setEnabled(false);
                TbLista.addMouseListener(new MouseAdapter() {
                    DefaultTableModel m = new DefaultTableModel();
                    @Override
                public void mouseClicked(MouseEvent e) {
                    tb_indice = TbLista.getSelectedRow();
                    BtSeleccionar.setEnabled(true);
                    System.out.println(tb_indice);
                    }
            });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TbLista = new javax.swing.JTable();
        LbTitulo = new javax.swing.JLabel();
        LbImg = new javax.swing.JLabel();
        LbDescripcion = new javax.swing.JLabel();
        LbConsulta = new javax.swing.JLabel();
        CbConsulta = new javax.swing.JComboBox<>();
        BtAgregar = new javax.swing.JButton();
        BtSeleccionar = new javax.swing.JButton();
        LbEstado = new javax.swing.JLabel();
        BtAtras = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Lista de registros");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setIconImage(ClasePrincipal.favicon);

        TbLista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "DefaultMain", "Default1", "Default2", "Default3", "Default4"
            }
        ));
        TbLista.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        TbLista.getTableHeader().setReorderingAllowed(false);
        TbLista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TbListaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TbLista);

        LbTitulo.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        LbTitulo.setText("Panel Directivo");

        LbImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finallogica/Interfaz/img/decoadmin.png"))); // NOI18N
        LbImg.setText("LogoAdmin");
        LbImg.setPreferredSize(new java.awt.Dimension(262, 120));

        LbDescripcion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LbDescripcion.setText("Vista general, todos los datos");

        LbConsulta.setText("Registro:");

        CbConsulta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Estudiantes", "Directivos", "Pregrados", "Posgrados" }));
        CbConsulta.setSelectedItem(null);
        CbConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbConsultaActionPerformed(evt);
            }
        });

        BtAgregar.setText("Agregar");
        BtAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtAgregarActionPerformed(evt);
            }
        });

        BtSeleccionar.setText("Confirmar");
        BtSeleccionar.setEnabled(false);
        BtSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtSeleccionarActionPerformed(evt);
            }
        });

        LbEstado.setText("Selecciona una entrada de la tabla para ver sus propiedades y acciones.");
        LbEstado.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        BtAtras.setText("Regresar");
        BtAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtAtrasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LbTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LbDescripcion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LbConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CbConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BtAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LbImg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BtSeleccionar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LbEstado, javax.swing.GroupLayout.DEFAULT_SIZE, 385, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BtAtras)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(LbImg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(LbDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(LbTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CbConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LbConsulta)
                            .addComponent(BtAgregar))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtAtras)
                    .addComponent(LbEstado)
                    .addComponent(BtSeleccionar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CbConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbConsultaActionPerformed
        actualizarTablas();
    }//GEN-LAST:event_CbConsultaActionPerformed

    private void BtSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtSeleccionarActionPerformed
        BtSeleccionar.setEnabled(false);
        VentanaRegistros registro = new VentanaRegistros(tipo, tb_indice);
        registro.setVisible(true);
                registro.addComponentListener(new ComponentAdapter() {
            @Override
            public void componentHidden(ComponentEvent e) {
                 registro.dispose();
                 actualizarTablas();
            }
        });
        
    }//GEN-LAST:event_BtSeleccionarActionPerformed

    private void TbListaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TbListaMouseClicked
        // Este código va a ver si se hizo click a la tabla, y depronto, que elemento se seleccionó.        
    }//GEN-LAST:event_TbListaMouseClicked

    private void BtAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtAtrasActionPerformed
        this.dispose();
    }//GEN-LAST:event_BtAtrasActionPerformed

    private void BtAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtAgregarActionPerformed
        if (CbConsulta.getSelectedIndex() >= 0) {
        Asistente agregar = new Asistente(CbConsulta.getSelectedIndex());
        agregar.setVisible(true);
                        agregar.addComponentListener(new ComponentAdapter() {
            @Override
            public void componentHidden(ComponentEvent e) {
                 agregar.dispose();
                 actualizarTablas();
            }
        });
        
        }
    }//GEN-LAST:event_BtAgregarActionPerformed

    private void actualizarTablas() {
                tipo = CbConsulta.getItemAt(CbConsulta.getSelectedIndex());
        switch (CbConsulta.getSelectedIndex()) {
            case 0:
                TbLista.setModel(new Mod_Estudiante(ClasePrincipal.estudiante));
                break;
            case 1:
                System.out.println("No implementado...");
                break;
            case 2:
                TbLista.setModel(new Mod_Pregrado(ClasePrincipal.pregrado));

                break;
            case 3:
                TbLista.setModel(new Mod_Posgrado(ClasePrincipal.posgrado));
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TablaRegistros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TablaRegistros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TablaRegistros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TablaRegistros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TablaRegistros().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtAgregar;
    private javax.swing.JButton BtAtras;
    private javax.swing.JButton BtSeleccionar;
    private javax.swing.JComboBox<String> CbConsulta;
    private javax.swing.JLabel LbConsulta;
    private javax.swing.JLabel LbDescripcion;
    private javax.swing.JLabel LbEstado;
    private javax.swing.JLabel LbImg;
    private javax.swing.JLabel LbTitulo;
    private javax.swing.JTable TbLista;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
