/*
 * 
 */
package finallogica.Interfaz.Registros;

import finallogica.Clases.Estudiante;
import finallogica.Clases.Fijas.Posgrado;
import finallogica.Clases.Fijas.Pregrado;
import finallogica.Interfaz.ClasePrincipal;
import finallogica.Modelo.Operaciones;
import javax.swing.JOptionPane;

/**
 *
 * @author AntJZ
 */
public class VentanaRegistros extends javax.swing.JFrame {

    private String tipo;
    private int index;
    private Object who;
    /**
     * Creates new form VentanaRegistros
     */


    public VentanaRegistros(String tipo, int index) {
        this.tipo = tipo;
        this.index = index;
        initComponents();
        
       LbTitulo.setText(this.tipo);
        if (this.tipo.equals("Estudiantes")) {
            Estudiante e = ClasePrincipal.estudiante.get(index);
            who = e;
            LbDescripcion.setText(String.valueOf(e.getCodigo()));
            
            Info1.setBorder(javax.swing.BorderFactory.createTitledBorder("Nombre"));
            Info1.setText(e.getNombre());
            Info2.setBorder(javax.swing.BorderFactory.createTitledBorder("Apellido"));
            Info2.setText(e.getApellido());
            Info3.setBorder(javax.swing.BorderFactory.createTitledBorder("Num. Documento"));
            Info3.setText(e.getNumero_documento());
            Info4.setBorder(javax.swing.BorderFactory.createTitledBorder("Num. Teléfono"));
            Info4.setText(e.getNumero_telefono());
            
        } else if (this.tipo.equals("Directivos")) {
            // Si ya está implementado en el código principal, fue que no hice esta interfaz todavía
            // Sorry ma people... (Antonio)
            
        } else if (this.tipo.equals("Pregrados")) {
            Pregrado p = ClasePrincipal.pregrado.get(index);
            LbDescripcion.setText(String.valueOf(p.getCodigo()));
            who = p;
            
            Info1.setBorder(javax.swing.BorderFactory.createTitledBorder("Nombre"));
            Info1.setText(p.getNombre());
            Info2.setBorder(javax.swing.BorderFactory.createTitledBorder("Facultad"));
            Info2.setText(String.valueOf(p.getFacultades()));
            Info3.setVisible(false); Info4.setVisible(false);
        } else if (this.tipo.equals("Posgrados")) {
            Posgrado p = ClasePrincipal.posgrado.get(index);
            LbDescripcion.setText(String.valueOf(p.getCodigo()));
            who = p;
            Info1.setBorder(javax.swing.BorderFactory.createTitledBorder("Nombre"));
            Info1.setText(p.getNombre());
            Info2.setBorder(javax.swing.BorderFactory.createTitledBorder("Facultad"));
            Info2.setText(String.valueOf(p.getFacultades()));
            Info3.setBorder(javax.swing.BorderFactory.createTitledBorder("Tipo"));
            Info3.setText(String.valueOf(p.getTipo_posgrado()));
            Info4.setVisible(false);
        } else {
            JOptionPane.showMessageDialog(null, "Corre el programa desde la clase principal, ya que no se han cargado aún los datos...");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LbImg = new javax.swing.JLabel();
        LbTitulo = new javax.swing.JLabel();
        LbTextID = new javax.swing.JLabel();
        BtCerrar = new javax.swing.JButton();
        BtModificar = new javax.swing.JButton();
        BtEliminar = new javax.swing.JButton();
        Panel = new javax.swing.JPanel();
        Info1 = new javax.swing.JLabel();
        Info2 = new javax.swing.JLabel();
        Info3 = new javax.swing.JLabel();
        Info4 = new javax.swing.JLabel();
        LbDescripcion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Propiedades");
        setIconImage(ClasePrincipal.favicon);

        LbImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finallogica/Interfaz/img/decoadmin.png"))); // NOI18N
        LbImg.setText("LogoAdmin");
        LbImg.setPreferredSize(new java.awt.Dimension(262, 120));

        LbTitulo.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        LbTitulo.setText("Tipo");

        LbTextID.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LbTextID.setText("ID:");

        BtCerrar.setText("Cerrar");
        BtCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtCerrarActionPerformed(evt);
            }
        });

        BtModificar.setText("Modificar");
        BtModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtModificarActionPerformed(evt);
            }
        });

        BtEliminar.setForeground(new java.awt.Color(153, 0, 51));
        BtEliminar.setText("Eliminar");
        BtEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtEliminarActionPerformed(evt);
            }
        });

        Panel.setBorder(javax.swing.BorderFactory.createTitledBorder("Resumen"));
        Panel.setPreferredSize(new java.awt.Dimension(47, 200));

        Info1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Info1.setText("Field");
        Info1.setBorder(javax.swing.BorderFactory.createTitledBorder("Title"));

        Info2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Info2.setText("Field");
        Info2.setBorder(javax.swing.BorderFactory.createTitledBorder("Title"));

        Info3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Info3.setText("Field");
        Info3.setBorder(javax.swing.BorderFactory.createTitledBorder("Title"));

        Info4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Info4.setText("Field");
        Info4.setBorder(javax.swing.BorderFactory.createTitledBorder("Title"));

        javax.swing.GroupLayout PanelLayout = new javax.swing.GroupLayout(Panel);
        Panel.setLayout(PanelLayout);
        PanelLayout.setHorizontalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Info1)
                    .addComponent(Info3)
                    .addComponent(Info2)
                    .addComponent(Info4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelLayout.setVerticalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLayout.createSequentialGroup()
                .addComponent(Info1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Info2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Info3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Info4)
                .addGap(0, 23, Short.MAX_VALUE))
        );

        LbDescripcion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LbDescripcion.setText("Código");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LbTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LbTextID)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LbDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(LbImg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Panel, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BtModificar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BtEliminar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BtCerrar)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LbImg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(LbTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LbTextID, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LbDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Panel, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtCerrar)
                    .addComponent(BtModificar)
                    .addComponent(BtEliminar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtCerrarActionPerformed
        this.dispose();
    }//GEN-LAST:event_BtCerrarActionPerformed

    private void BtEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtEliminarActionPerformed
         int r = JOptionPane.showConfirmDialog(null, "Está seguro que quiere eliminar el estudiante?\nEsto puede dejar datos huérfanos...", "Confirmación", JOptionPane.YES_NO_OPTION);
        if (r == 0) {
            if (Operaciones.eliminarRegistro(who)) {
            this.dispose();
            } else {
                JOptionPane.showMessageDialog(null, "El estudiante no pudo ser eliminado.\nEs todo lo que sé...", "Error", JOptionPane.ERROR_MESSAGE);
            }
            
        } else {
            System.out.println("Cancelado...");
        }
    }//GEN-LAST:event_BtEliminarActionPerformed

    private void BtModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtModificarActionPerformed
        AsistenteModificacion mod = new AsistenteModificacion(who);
        mod.setVisible(true);
    }//GEN-LAST:event_BtModificarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaRegistros("Lorem Ipsum", 0).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtCerrar;
    private javax.swing.JButton BtEliminar;
    private javax.swing.JButton BtModificar;
    private javax.swing.JLabel Info1;
    private javax.swing.JLabel Info2;
    private javax.swing.JLabel Info3;
    private javax.swing.JLabel Info4;
    private javax.swing.JLabel LbDescripcion;
    private javax.swing.JLabel LbImg;
    private javax.swing.JLabel LbTextID;
    private javax.swing.JLabel LbTitulo;
    private javax.swing.JPanel Panel;
    // End of variables declaration//GEN-END:variables
}
